spring:
  application:
    name: swift-bill-sb-free

  datasource:
    url: jdbc:mysql://localhost:3306/swiftbillfree?createDatabaseIfNotExist=true
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

  flyway:
    enabled: false
    locations: classpath:db/migration
    default-schema: trialswiftbill
    baseline-on-migrate: true

app:
  request-prefix: /api/v1
  basic-qrcode-base-url: https://api.vietqr.io/image/
  basic-qrcode-template-id: 20jhRcP
